openapi: 3.1.0
info:
  title: Service-to-Service Communication PoC - REST APIs
  version: 1.0.0
  description: |
    REST API contracts for the PoC microservices.
    Each service exposes its own REST API; this document consolidates
    all REST contracts for reference.

servers:
  - url: http://localhost:30080
    description: API Gateway (Kind cluster)
  - url: http://localhost:8081
    description: Order Service (local dev)
  - url: http://localhost:8082
    description: Product Service (local dev)
  - url: http://localhost:8083
    description: Payment Service (local dev)

paths:
  # ── Order Service ──────────────────────────────────────────
  /api/v1/orders:
    post:
      summary: Create a new order
      operationId: createOrder
      tags: [Order]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or missing JWT
        '429':
          description: Rate limit exceeded

    get:
      summary: List orders
      operationId: listOrders
      tags: [Order]
      security:
        - bearerAuth: []
      parameters:
        - name: customerId
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/OrderStatus'
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'

  /api/v1/orders/{orderId}:
    get:
      summary: Get order by ID
      operationId: getOrder
      tags: [Order]
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order not found

  # ── Product Service ────────────────────────────────────────
  /api/v1/products:
    get:
      summary: List products
      operationId: listProducts
      tags: [Product]
      parameters:
        - name: category
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'

  /api/v1/products/{productId}:
    get:
      summary: Get product by ID
      operationId: getProduct
      tags: [Product]
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '404':
          description: Product not found

  /api/v1/products/{productId}/inventory:
    get:
      summary: Check product inventory
      operationId: checkInventory
      tags: [Product]
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
        - name: quantity
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Inventory check result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryResponse'

  # ── Payment Service ────────────────────────────────────────
  /api/v1/payments:
    post:
      summary: Process a payment
      operationId: processPayment
      tags: [Payment]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: Payment processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Invalid payment request
        '503':
          description: Payment service unavailable (circuit breaker)

  /api/v1/payments/{paymentId}:
    get:
      summary: Get payment status
      operationId: getPayment
      tags: [Payment]
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Payment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '404':
          description: Payment not found

  # ── Health Checks (all services) ───────────────────────────
  /actuator/health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      tags: [Infrastructure]
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [UP, DOWN]

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # ── Order Schemas ──────────────────────────────────────
    CreateOrderRequest:
      type: object
      required: [productId, quantity, customerId]
      properties:
        productId:
          type: string
          example: "prod-001"
        quantity:
          type: integer
          minimum: 1
          example: 2
        customerId:
          type: string
          example: "cust-001"

    OrderResponse:
      type: object
      properties:
        id:
          type: string
          example: "ord-001"
        customerId:
          type: string
        productId:
          type: string
        quantity:
          type: integer
        totalAmount:
          $ref: '#/components/schemas/Money'
        status:
          $ref: '#/components/schemas/OrderStatus'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    OrderStatus:
      type: string
      enum: [CREATED, PAYMENT_PENDING, PAID, SHIPPED]

    # ── Product Schemas ────────────────────────────────────
    ProductResponse:
      type: object
      properties:
        id:
          type: string
          example: "prod-001"
        name:
          type: string
          example: "Wireless Mouse"
        description:
          type: string
        price:
          $ref: '#/components/schemas/Money'
        stock:
          type: integer
          example: 150
        category:
          type: string
          example: "ELECTRONICS"

    InventoryResponse:
      type: object
      properties:
        available:
          type: boolean
        remainingStock:
          type: integer

    # ── Payment Schemas ────────────────────────────────────
    PaymentRequest:
      type: object
      required: [orderId, amount]
      properties:
        orderId:
          type: string
          example: "ord-001"
        amount:
          $ref: '#/components/schemas/Money'

    PaymentResponse:
      type: object
      properties:
        id:
          type: string
          example: "pay-001"
        orderId:
          type: string
        amount:
          $ref: '#/components/schemas/Money'
        status:
          $ref: '#/components/schemas/PaymentStatus'
        createdAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
          nullable: true
        message:
          type: string
          description: Fallback message when circuit breaker is open
          nullable: true

    PaymentStatus:
      type: string
      enum: [PENDING, COMPLETED, FAILED]

    # ── Shared Schemas ─────────────────────────────────────
    Money:
      type: object
      properties:
        amount:
          type: number
          format: double
          example: 29.99
        currency:
          type: string
          default: "USD"
          example: "USD"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        traceId:
          type: string
          description: Distributed trace ID for debugging
