kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: s2s-comm-poc
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # API Gateway (APISIX)
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      # Jaeger UI
      - containerPort: 16686
        hostPort: 16686
        protocol: TCP
      # Grafana
      - containerPort: 3000
        hostPort: 3000
        protocol: TCP
      # Prometheus
      - containerPort: 9090
        hostPort: 9090
        protocol: TCP
  - role: worker
  - role: worker
